// Generated by scripts/dev/regional-model-library/export-baijiabao-review-only-workflow-candidate-desk-snapshot.mjs
// Source artifact: .tmp/regional-model-library/out/artifacts/baijiabao-review-only-workflow-candidate/baijiabao-review-only-workflow-candidate.json

export const baijiabaoReviewQueueSnapshot = {
  "generatedAt": "2026-04-24T21:11:42.809Z",
  "artifactKey": "baijiabao.review-only.workflow-candidate.model-review.v1",
  "status": "review-candidate",
  "sourceSummary": {
    "decisionStatus": "manual-review-supports-review-only-workflow",
    "reviewedItems": 24,
    "reviewPrecision": 0.5833333333333334,
    "winterUsefulRatio": 0.6153846153846154,
    "invalidRows": 0
  },
  "productGate": {
    "reviewOnlyWorkflowCandidate": true,
    "runtimePromotionAllowed": false,
    "requiresHumanConfirmationBeforeUserFacingClaim": true
  },
  "runtimeBoundary": {
    "topLevelRiskScoreForbidden": true,
    "topLevelRiskLevelForbidden": true,
    "runtimeRegistryEligible": false,
    "promotionEligible": false,
    "postgresSchemaChangeRequired": false
  },
  "summary": {
    "itemCount": 24,
    "bySeverity": [
      {
        "key": "medium",
        "count": 11
      },
      {
        "key": "needs-evidence",
        "count": 7
      },
      {
        "key": "high",
        "count": 3
      },
      {
        "key": "low",
        "count": 3
      }
    ],
    "byRecommendedAction": [
      {
        "key": "request-raw-evidence",
        "count": 7
      },
      {
        "key": "review-process-evidence",
        "count": 7
      },
      {
        "key": "review-label-window",
        "count": 4
      },
      {
        "key": "archive-as-control",
        "count": 3
      },
      {
        "key": "prioritize-manual-review",
        "count": 3
      }
    ],
    "byAutoClass": [
      {
        "key": "process_related",
        "count": 7
      },
      {
        "key": "unclear",
        "count": 7
      },
      {
        "key": "label_boundary_artifact",
        "count": 4
      },
      {
        "key": "expected_noise",
        "count": 3
      },
      {
        "key": "true_pre_signal",
        "count": 3
      }
    ],
    "byPoint": [
      {
        "key": "ZD3",
        "count": 10
      },
      {
        "key": "ZD1",
        "count": 7
      },
      {
        "key": "ZD2",
        "count": 7
      }
    ]
  },
  "items": [
    {
      "queueItemId": "baijiabao-review-only:ZD1:run:4",
      "sourceReviewItemId": "ZD1:run:4",
      "pointId": "ZD1",
      "priority": 1,
      "severity": "high",
      "recommendedAction": "prioritize-manual-review",
      "status": "review-candidate",
      "window": {
        "startTs": "2023-10-20T16:00:00.000Z",
        "endTs": "2023-12-08T16:00:00.000Z",
        "durationDays": 50,
        "seasonSet": "autumn|winter",
        "monthSet": "2023-10|2023-11|2023-12"
      },
      "evidenceSummary": {
        "utilityClass": "contains-immediate-positive",
        "classificationMix": "grey-zone-pre-episode:26|hard-negative-within-30d-next-positive:16|hard-negative-no-positive-within-30d:6|immediate-positive:2",
        "evidenceRowCount": 50,
        "immediatePositiveDays": 2,
        "greyZoneDays": 26,
        "within30Days": 16,
        "isolatedDays": 6,
        "maxBoosterScore": 0.5677060576086368
      },
      "autoReview": {
        "finalClass": "true_pre_signal",
        "useful": "yes",
        "confidence": "high",
        "rule": "strict-immediate-positive-with-displacement-and-trigger",
        "rawEvidenceNeeded": "no",
        "warning": "模型复核候选，需人工确认后发布。"
      }
    },
    {
      "queueItemId": "baijiabao-review-only:ZD2:run:26",
      "sourceReviewItemId": "ZD2:run:26",
      "pointId": "ZD2",
      "priority": 2,
      "severity": "high",
      "recommendedAction": "prioritize-manual-review",
      "status": "review-candidate",
      "window": {
        "startTs": "2024-09-05T16:00:00.000Z",
        "endTs": "2024-10-18T16:00:00.000Z",
        "durationDays": 44,
        "seasonSet": "autumn",
        "monthSet": "2024-09|2024-10"
      },
      "evidenceSummary": {
        "utilityClass": "contains-immediate-positive",
        "classificationMix": "grey-zone-pre-episode:38|hard-negative-within-30d-next-positive:4|immediate-positive:2",
        "evidenceRowCount": 44,
        "immediatePositiveDays": 2,
        "greyZoneDays": 38,
        "within30Days": 4,
        "isolatedDays": 0,
        "maxBoosterScore": 0.46733900472976697
      },
      "autoReview": {
        "finalClass": "true_pre_signal",
        "useful": "yes",
        "confidence": "high",
        "rule": "strict-immediate-positive-with-displacement-and-trigger",
        "rawEvidenceNeeded": "no",
        "warning": "模型复核候选，需人工确认后发布。"
      }
    },
    {
      "queueItemId": "baijiabao-review-only:ZD2:run:24",
      "sourceReviewItemId": "ZD2:run:24",
      "pointId": "ZD2",
      "priority": 3,
      "severity": "medium",
      "recommendedAction": "review-process-evidence",
      "status": "review-candidate",
      "window": {
        "startTs": "2023-12-30T16:00:00.000Z",
        "endTs": "2024-01-30T16:00:00.000Z",
        "durationDays": 32,
        "seasonSet": "winter",
        "monthSet": "2023-12|2024-01"
      },
      "evidenceSummary": {
        "utilityClass": "contains-immediate-positive",
        "classificationMix": "grey-zone-pre-episode:27|hard-negative-within-30d-next-positive:4|immediate-positive:1",
        "evidenceRowCount": 32,
        "immediatePositiveDays": 1,
        "greyZoneDays": 27,
        "within30Days": 4,
        "isolatedDays": 0,
        "maxBoosterScore": 0.49203198369893597
      },
      "autoReview": {
        "finalClass": "process_related",
        "useful": "yes",
        "confidence": "medium",
        "rule": "pre-episode-or-within30-process-related",
        "rawEvidenceNeeded": "yes",
        "warning": "模型复核候选，需人工确认后发布。"
      }
    },
    {
      "queueItemId": "baijiabao-review-only:ZD3:run:58",
      "sourceReviewItemId": "ZD3:run:58",
      "pointId": "ZD3",
      "priority": 4,
      "severity": "medium",
      "recommendedAction": "review-process-evidence",
      "status": "review-candidate",
      "window": {
        "startTs": "2024-11-21T16:00:00.000Z",
        "endTs": "2024-12-06T16:00:00.000Z",
        "durationDays": 16,
        "seasonSet": "autumn|winter",
        "monthSet": "2024-11|2024-12"
      },
      "evidenceSummary": {
        "utilityClass": "contains-immediate-positive",
        "classificationMix": "grey-zone-pre-episode:15|immediate-positive:1",
        "evidenceRowCount": 16,
        "immediatePositiveDays": 1,
        "greyZoneDays": 15,
        "within30Days": 0,
        "isolatedDays": 0,
        "maxBoosterScore": 0.49772299404084647
      },
      "autoReview": {
        "finalClass": "process_related",
        "useful": "yes",
        "confidence": "low",
        "rule": "pre-episode-or-within30-process-related",
        "rawEvidenceNeeded": "yes",
        "warning": "模型复核候选，需人工确认后发布。"
      }
    },
    {
      "queueItemId": "baijiabao-review-only:ZD1:run:11",
      "sourceReviewItemId": "ZD1:run:11",
      "pointId": "ZD1",
      "priority": 5,
      "severity": "medium",
      "recommendedAction": "review-process-evidence",
      "status": "review-candidate",
      "window": {
        "startTs": "2024-09-05T16:00:00.000Z",
        "endTs": "2024-09-28T16:00:00.000Z",
        "durationDays": 24,
        "seasonSet": "autumn",
        "monthSet": "2024-09"
      },
      "evidenceSummary": {
        "utilityClass": "contains-immediate-positive",
        "classificationMix": "grey-zone-pre-episode:14|hard-negative-within-30d-next-positive:9|immediate-positive:1",
        "evidenceRowCount": 24,
        "immediatePositiveDays": 1,
        "greyZoneDays": 14,
        "within30Days": 9,
        "isolatedDays": 0,
        "maxBoosterScore": 0.4326931878094818
      },
      "autoReview": {
        "finalClass": "process_related",
        "useful": "yes",
        "confidence": "medium",
        "rule": "pre-episode-or-within30-process-related",
        "rawEvidenceNeeded": "yes",
        "warning": "模型复核候选，需人工确认后发布。"
      }
    },
    {
      "queueItemId": "baijiabao-review-only:ZD3:run:50",
      "sourceReviewItemId": "ZD3:run:50",
      "pointId": "ZD3",
      "priority": 6,
      "severity": "high",
      "recommendedAction": "prioritize-manual-review",
      "status": "review-candidate",
      "window": {
        "startTs": "2024-09-13T16:00:00.000Z",
        "endTs": "2024-09-28T16:00:00.000Z",
        "durationDays": 16,
        "seasonSet": "autumn",
        "monthSet": "2024-09"
      },
      "evidenceSummary": {
        "utilityClass": "contains-immediate-positive",
        "classificationMix": "grey-zone-pre-episode:7|hard-negative-within-30d-next-positive:7|immediate-positive:2",
        "evidenceRowCount": 16,
        "immediatePositiveDays": 2,
        "greyZoneDays": 7,
        "within30Days": 7,
        "isolatedDays": 0,
        "maxBoosterScore": 0.4789416558127233
      },
      "autoReview": {
        "finalClass": "true_pre_signal",
        "useful": "yes",
        "confidence": "high",
        "rule": "strict-immediate-positive-with-displacement-and-trigger",
        "rawEvidenceNeeded": "no",
        "warning": "模型复核候选，需人工确认后发布。"
      }
    },
    {
      "queueItemId": "baijiabao-review-only:ZD2:run:18",
      "sourceReviewItemId": "ZD2:run:18",
      "pointId": "ZD2",
      "priority": 7,
      "severity": "medium",
      "recommendedAction": "review-process-evidence",
      "status": "review-candidate",
      "window": {
        "startTs": "2023-10-05T16:00:00.000Z",
        "endTs": "2023-11-09T16:00:00.000Z",
        "durationDays": 36,
        "seasonSet": "autumn",
        "monthSet": "2023-10|2023-11"
      },
      "evidenceSummary": {
        "utilityClass": "contains-immediate-positive",
        "classificationMix": "grey-zone-pre-episode:16|hard-negative-within-30d-next-positive:16|hard-negative-no-positive-within-30d:3|immediate-positive:1",
        "evidenceRowCount": 36,
        "immediatePositiveDays": 1,
        "greyZoneDays": 16,
        "within30Days": 16,
        "isolatedDays": 3,
        "maxBoosterScore": 0.5678321357807389
      },
      "autoReview": {
        "finalClass": "process_related",
        "useful": "yes",
        "confidence": "medium",
        "rule": "pre-episode-or-within30-process-related",
        "rawEvidenceNeeded": "yes",
        "warning": "模型复核候选，需人工确认后发布。"
      }
    },
    {
      "queueItemId": "baijiabao-review-only:ZD3:run:59",
      "sourceReviewItemId": "ZD3:run:59",
      "pointId": "ZD3",
      "priority": 8,
      "severity": "medium",
      "recommendedAction": "review-process-evidence",
      "status": "review-candidate",
      "window": {
        "startTs": "2024-12-13T16:00:00.000Z",
        "endTs": "2024-12-23T16:00:00.000Z",
        "durationDays": 11,
        "seasonSet": "winter",
        "monthSet": "2024-12"
      },
      "evidenceSummary": {
        "utilityClass": "contains-immediate-positive",
        "classificationMix": "grey-zone-pre-episode:9|immediate-positive:2",
        "evidenceRowCount": 11,
        "immediatePositiveDays": 2,
        "greyZoneDays": 9,
        "within30Days": 0,
        "isolatedDays": 0,
        "maxBoosterScore": 0.49366134837675935
      },
      "autoReview": {
        "finalClass": "process_related",
        "useful": "yes",
        "confidence": "low",
        "rule": "pre-episode-or-within30-process-related",
        "rawEvidenceNeeded": "yes",
        "warning": "模型复核候选，需人工确认后发布。"
      }
    },
    {
      "queueItemId": "baijiabao-review-only:ZD2:run:20",
      "sourceReviewItemId": "ZD2:run:20",
      "pointId": "ZD2",
      "priority": 9,
      "severity": "medium",
      "recommendedAction": "review-process-evidence",
      "status": "review-candidate",
      "window": {
        "startTs": "2023-11-16T16:00:00.000Z",
        "endTs": "2023-11-28T16:00:00.000Z",
        "durationDays": 13,
        "seasonSet": "autumn",
        "monthSet": "2023-11"
      },
      "evidenceSummary": {
        "utilityClass": "contains-pre-episode-grey-zone",
        "classificationMix": "grey-zone-pre-episode:8|hard-negative-within-30d-next-positive:5",
        "evidenceRowCount": 13,
        "immediatePositiveDays": 0,
        "greyZoneDays": 8,
        "within30Days": 5,
        "isolatedDays": 0,
        "maxBoosterScore": 0.5312885500629538
      },
      "autoReview": {
        "finalClass": "process_related",
        "useful": "yes",
        "confidence": "low",
        "rule": "pre-episode-or-within30-process-related",
        "rawEvidenceNeeded": "yes",
        "warning": "模型复核候选，需人工确认后发布。"
      }
    },
    {
      "queueItemId": "baijiabao-review-only:ZD1:run:7",
      "sourceReviewItemId": "ZD1:run:7",
      "pointId": "ZD1",
      "priority": 10,
      "severity": "medium",
      "recommendedAction": "review-label-window",
      "status": "review-candidate",
      "window": {
        "startTs": "2024-01-08T16:00:00.000Z",
        "endTs": "2024-01-14T16:00:00.000Z",
        "durationDays": 7,
        "seasonSet": "winter",
        "monthSet": "2024-01"
      },
      "evidenceSummary": {
        "utilityClass": "contains-pre-episode-grey-zone",
        "classificationMix": "hard-negative-within-30d-next-positive:5|grey-zone-pre-episode:2",
        "evidenceRowCount": 7,
        "immediatePositiveDays": 0,
        "greyZoneDays": 2,
        "within30Days": 5,
        "isolatedDays": 0,
        "maxBoosterScore": 0.47647111458152813
      },
      "autoReview": {
        "finalClass": "label_boundary_artifact",
        "useful": "yes",
        "confidence": "low",
        "rule": "label-boundary-near-event",
        "rawEvidenceNeeded": "yes",
        "warning": "模型复核候选，需人工确认后发布。"
      }
    },
    {
      "queueItemId": "baijiabao-review-only:ZD3:run:49",
      "sourceReviewItemId": "ZD3:run:49",
      "pointId": "ZD3",
      "priority": 11,
      "severity": "medium",
      "recommendedAction": "review-label-window",
      "status": "review-candidate",
      "window": {
        "startTs": "2024-09-07T16:00:00.000Z",
        "endTs": "2024-09-10T16:00:00.000Z",
        "durationDays": 4,
        "seasonSet": "autumn",
        "monthSet": "2024-09"
      },
      "evidenceSummary": {
        "utilityClass": "contains-pre-episode-grey-zone",
        "classificationMix": "grey-zone-pre-episode:4",
        "evidenceRowCount": 4,
        "immediatePositiveDays": 0,
        "greyZoneDays": 4,
        "within30Days": 0,
        "isolatedDays": 0,
        "maxBoosterScore": 0.3800081367686432
      },
      "autoReview": {
        "finalClass": "label_boundary_artifact",
        "useful": "yes",
        "confidence": "low",
        "rule": "label-boundary-near-event",
        "rawEvidenceNeeded": "yes",
        "warning": "模型复核候选，需人工确认后发布。"
      }
    },
    {
      "queueItemId": "baijiabao-review-only:ZD2:run:19",
      "sourceReviewItemId": "ZD2:run:19",
      "pointId": "ZD2",
      "priority": 12,
      "severity": "needs-evidence",
      "recommendedAction": "request-raw-evidence",
      "status": "review-candidate",
      "window": {
        "startTs": "2023-11-12T16:00:00.000Z",
        "endTs": "2023-11-13T16:00:00.000Z",
        "durationDays": 2,
        "seasonSet": "autumn",
        "monthSet": "2023-11"
      },
      "evidenceSummary": {
        "utilityClass": "contains-pre-episode-grey-zone",
        "classificationMix": "grey-zone-pre-episode:2",
        "evidenceRowCount": 2,
        "immediatePositiveDays": 0,
        "greyZoneDays": 2,
        "within30Days": 0,
        "isolatedDays": 0,
        "maxBoosterScore": 0.5272524786253661
      },
      "autoReview": {
        "finalClass": "unclear",
        "useful": "unsure",
        "confidence": "low",
        "rule": "insufficient-auto-evidence",
        "rawEvidenceNeeded": "yes",
        "warning": "模型复核候选，需人工确认后发布。"
      }
    },
    {
      "queueItemId": "baijiabao-review-only:ZD3:run:56",
      "sourceReviewItemId": "ZD3:run:56",
      "pointId": "ZD3",
      "priority": 13,
      "severity": "needs-evidence",
      "recommendedAction": "request-raw-evidence",
      "status": "review-candidate",
      "window": {
        "startTs": "2024-11-05T16:00:00.000Z",
        "endTs": "2024-11-06T16:00:00.000Z",
        "durationDays": 2,
        "seasonSet": "autumn",
        "monthSet": "2024-11"
      },
      "evidenceSummary": {
        "utilityClass": "contains-pre-episode-grey-zone",
        "classificationMix": "grey-zone-pre-episode:1|hard-negative-within-30d-next-positive:1",
        "evidenceRowCount": 2,
        "immediatePositiveDays": 0,
        "greyZoneDays": 1,
        "within30Days": 1,
        "isolatedDays": 0,
        "maxBoosterScore": 0.4848663191528783
      },
      "autoReview": {
        "finalClass": "unclear",
        "useful": "unsure",
        "confidence": "low",
        "rule": "insufficient-auto-evidence",
        "rawEvidenceNeeded": "yes",
        "warning": "模型复核候选，需人工确认后发布。"
      }
    },
    {
      "queueItemId": "baijiabao-review-only:ZD2:run:23",
      "sourceReviewItemId": "ZD2:run:23",
      "pointId": "ZD2",
      "priority": 14,
      "severity": "medium",
      "recommendedAction": "review-process-evidence",
      "status": "review-candidate",
      "window": {
        "startTs": "2023-12-16T16:00:00.000Z",
        "endTs": "2023-12-27T16:00:00.000Z",
        "durationDays": 12,
        "seasonSet": "winter",
        "monthSet": "2023-12"
      },
      "evidenceSummary": {
        "utilityClass": "contains-hard-negative-within-30d",
        "classificationMix": "hard-negative-within-30d-next-positive:12",
        "evidenceRowCount": 12,
        "immediatePositiveDays": 0,
        "greyZoneDays": 0,
        "within30Days": 12,
        "isolatedDays": 0,
        "maxBoosterScore": 0.50461071399821
      },
      "autoReview": {
        "finalClass": "process_related",
        "useful": "yes",
        "confidence": "low",
        "rule": "pre-episode-or-within30-process-related",
        "rawEvidenceNeeded": "yes",
        "warning": "模型复核候选，需人工确认后发布。"
      }
    },
    {
      "queueItemId": "baijiabao-review-only:ZD1:run:6",
      "sourceReviewItemId": "ZD1:run:6",
      "pointId": "ZD1",
      "priority": 15,
      "severity": "medium",
      "recommendedAction": "review-label-window",
      "status": "review-candidate",
      "window": {
        "startTs": "2023-12-30T16:00:00.000Z",
        "endTs": "2024-01-05T16:00:00.000Z",
        "durationDays": 7,
        "seasonSet": "winter",
        "monthSet": "2023-12|2024-01"
      },
      "evidenceSummary": {
        "utilityClass": "contains-hard-negative-within-30d",
        "classificationMix": "hard-negative-within-30d-next-positive:7",
        "evidenceRowCount": 7,
        "immediatePositiveDays": 0,
        "greyZoneDays": 0,
        "within30Days": 7,
        "isolatedDays": 0,
        "maxBoosterScore": 0.4941637208981082
      },
      "autoReview": {
        "finalClass": "label_boundary_artifact",
        "useful": "yes",
        "confidence": "low",
        "rule": "label-boundary-near-event",
        "rawEvidenceNeeded": "yes",
        "warning": "模型复核候选，需人工确认后发布。"
      }
    },
    {
      "queueItemId": "baijiabao-review-only:ZD1:run:10",
      "sourceReviewItemId": "ZD1:run:10",
      "pointId": "ZD1",
      "priority": 16,
      "severity": "medium",
      "recommendedAction": "review-label-window",
      "status": "review-candidate",
      "window": {
        "startTs": "2024-02-27T16:00:00.000Z",
        "endTs": "2024-02-29T16:00:00.000Z",
        "durationDays": 3,
        "seasonSet": "winter",
        "monthSet": "2024-02"
      },
      "evidenceSummary": {
        "utilityClass": "contains-hard-negative-within-30d",
        "classificationMix": "hard-negative-within-30d-next-positive:3",
        "evidenceRowCount": 3,
        "immediatePositiveDays": 0,
        "greyZoneDays": 0,
        "within30Days": 3,
        "isolatedDays": 0,
        "maxBoosterScore": 0.4547573392628651
      },
      "autoReview": {
        "finalClass": "label_boundary_artifact",
        "useful": "yes",
        "confidence": "low",
        "rule": "label-boundary-near-event",
        "rawEvidenceNeeded": "yes",
        "warning": "模型复核候选，需人工确认后发布。"
      }
    },
    {
      "queueItemId": "baijiabao-review-only:ZD3:run:46",
      "sourceReviewItemId": "ZD3:run:46",
      "pointId": "ZD3",
      "priority": 17,
      "severity": "needs-evidence",
      "recommendedAction": "request-raw-evidence",
      "status": "review-candidate",
      "window": {
        "startTs": "2024-02-08T16:00:00.000Z",
        "endTs": "2024-02-17T16:00:00.000Z",
        "durationDays": 10,
        "seasonSet": "winter",
        "monthSet": "2024-02"
      },
      "evidenceSummary": {
        "utilityClass": "contains-hard-negative-within-30d",
        "classificationMix": "hard-negative-no-positive-within-30d:9|hard-negative-within-30d-next-positive:1",
        "evidenceRowCount": 10,
        "immediatePositiveDays": 0,
        "greyZoneDays": 0,
        "within30Days": 1,
        "isolatedDays": 9,
        "maxBoosterScore": 0.4862879538395078
      },
      "autoReview": {
        "finalClass": "unclear",
        "useful": "unsure",
        "confidence": "low",
        "rule": "insufficient-auto-evidence",
        "rawEvidenceNeeded": "yes",
        "warning": "模型复核候选，需人工确认后发布。"
      }
    },
    {
      "queueItemId": "baijiabao-review-only:ZD3:run:47",
      "sourceReviewItemId": "ZD3:run:47",
      "pointId": "ZD3",
      "priority": 18,
      "severity": "needs-evidence",
      "recommendedAction": "request-raw-evidence",
      "status": "review-candidate",
      "window": {
        "startTs": "2024-02-24T16:00:00.000Z",
        "endTs": "2024-02-24T16:00:00.000Z",
        "durationDays": 1,
        "seasonSet": "winter",
        "monthSet": "2024-02"
      },
      "evidenceSummary": {
        "utilityClass": "contains-hard-negative-within-30d",
        "classificationMix": "hard-negative-within-30d-next-positive:1",
        "evidenceRowCount": 1,
        "immediatePositiveDays": 0,
        "greyZoneDays": 0,
        "within30Days": 1,
        "isolatedDays": 0,
        "maxBoosterScore": 0.4514702888817066
      },
      "autoReview": {
        "finalClass": "unclear",
        "useful": "unsure",
        "confidence": "low",
        "rule": "insufficient-auto-evidence",
        "rawEvidenceNeeded": "yes",
        "warning": "模型复核候选，需人工确认后发布。"
      }
    },
    {
      "queueItemId": "baijiabao-review-only:ZD1:run:15",
      "sourceReviewItemId": "ZD1:run:15",
      "pointId": "ZD1",
      "priority": 19,
      "severity": "low",
      "recommendedAction": "archive-as-control",
      "status": "review-candidate",
      "window": {
        "startTs": "2024-12-13T16:00:00.000Z",
        "endTs": "2024-12-30T16:00:00.000Z",
        "durationDays": 18,
        "seasonSet": "winter",
        "monthSet": "2024-12"
      },
      "evidenceSummary": {
        "utilityClass": "isolated-background-alert-run",
        "classificationMix": "hard-negative-no-positive-within-30d:18",
        "evidenceRowCount": 18,
        "immediatePositiveDays": 0,
        "greyZoneDays": 0,
        "within30Days": 0,
        "isolatedDays": 18,
        "maxBoosterScore": 0.4866217367057055
      },
      "autoReview": {
        "finalClass": "expected_noise",
        "useful": "no",
        "confidence": "medium",
        "rule": "isolated-background-or-low-evidence",
        "rawEvidenceNeeded": "yes",
        "warning": "模型复核候选，需人工确认后发布。"
      }
    },
    {
      "queueItemId": "baijiabao-review-only:ZD1:run:3",
      "sourceReviewItemId": "ZD1:run:3",
      "pointId": "ZD1",
      "priority": 20,
      "severity": "needs-evidence",
      "recommendedAction": "request-raw-evidence",
      "status": "review-candidate",
      "window": {
        "startTs": "2023-10-06T16:00:00.000Z",
        "endTs": "2023-10-17T16:00:00.000Z",
        "durationDays": 12,
        "seasonSet": "autumn",
        "monthSet": "2023-10"
      },
      "evidenceSummary": {
        "utilityClass": "isolated-background-alert-run",
        "classificationMix": "hard-negative-no-positive-within-30d:12",
        "evidenceRowCount": 12,
        "immediatePositiveDays": 0,
        "greyZoneDays": 0,
        "within30Days": 0,
        "isolatedDays": 12,
        "maxBoosterScore": 0.5557538320988077
      },
      "autoReview": {
        "finalClass": "unclear",
        "useful": "unsure",
        "confidence": "low",
        "rule": "insufficient-auto-evidence",
        "rawEvidenceNeeded": "yes",
        "warning": "模型复核候选，需人工确认后发布。"
      }
    },
    {
      "queueItemId": "baijiabao-review-only:ZD2:run:22",
      "sourceReviewItemId": "ZD2:run:22",
      "pointId": "ZD2",
      "priority": 21,
      "severity": "needs-evidence",
      "recommendedAction": "request-raw-evidence",
      "status": "review-candidate",
      "window": {
        "startTs": "2023-12-11T16:00:00.000Z",
        "endTs": "2023-12-13T16:00:00.000Z",
        "durationDays": 3,
        "seasonSet": "winter",
        "monthSet": "2023-12"
      },
      "evidenceSummary": {
        "utilityClass": "isolated-background-alert-run",
        "classificationMix": "hard-negative-no-positive-within-30d:3",
        "evidenceRowCount": 3,
        "immediatePositiveDays": 0,
        "greyZoneDays": 0,
        "within30Days": 0,
        "isolatedDays": 3,
        "maxBoosterScore": 0.5326395409547865
      },
      "autoReview": {
        "finalClass": "unclear",
        "useful": "unsure",
        "confidence": "low",
        "rule": "insufficient-auto-evidence",
        "rawEvidenceNeeded": "yes",
        "warning": "模型复核候选，需人工确认后发布。"
      }
    },
    {
      "queueItemId": "baijiabao-review-only:ZD3:run:38",
      "sourceReviewItemId": "ZD3:run:38",
      "pointId": "ZD3",
      "priority": 22,
      "severity": "low",
      "recommendedAction": "archive-as-control",
      "status": "review-candidate",
      "window": {
        "startTs": "2023-11-16T16:00:00.000Z",
        "endTs": "2023-11-23T16:00:00.000Z",
        "durationDays": 8,
        "seasonSet": "autumn",
        "monthSet": "2023-11"
      },
      "evidenceSummary": {
        "utilityClass": "isolated-background-alert-run",
        "classificationMix": "hard-negative-no-positive-within-30d:8",
        "evidenceRowCount": 8,
        "immediatePositiveDays": 0,
        "greyZoneDays": 0,
        "within30Days": 0,
        "isolatedDays": 8,
        "maxBoosterScore": 0.5237070286425157
      },
      "autoReview": {
        "finalClass": "expected_noise",
        "useful": "no",
        "confidence": "medium",
        "rule": "isolated-background-or-low-evidence",
        "rawEvidenceNeeded": "yes",
        "warning": "模型复核候选，需人工确认后发布。"
      }
    },
    {
      "queueItemId": "baijiabao-review-only:ZD3:run:42",
      "sourceReviewItemId": "ZD3:run:42",
      "pointId": "ZD3",
      "priority": 23,
      "severity": "low",
      "recommendedAction": "archive-as-control",
      "status": "review-candidate",
      "window": {
        "startTs": "2023-12-30T16:00:00.000Z",
        "endTs": "2024-01-05T16:00:00.000Z",
        "durationDays": 7,
        "seasonSet": "winter",
        "monthSet": "2023-12|2024-01"
      },
      "evidenceSummary": {
        "utilityClass": "isolated-background-alert-run",
        "classificationMix": "hard-negative-no-positive-within-30d:7",
        "evidenceRowCount": 7,
        "immediatePositiveDays": 0,
        "greyZoneDays": 0,
        "within30Days": 0,
        "isolatedDays": 7,
        "maxBoosterScore": 0.4851357582017467
      },
      "autoReview": {
        "finalClass": "expected_noise",
        "useful": "no",
        "confidence": "medium",
        "rule": "isolated-background-or-low-evidence",
        "rawEvidenceNeeded": "yes",
        "warning": "模型复核候选，需人工确认后发布。"
      }
    },
    {
      "queueItemId": "baijiabao-review-only:ZD3:run:34",
      "sourceReviewItemId": "ZD3:run:34",
      "pointId": "ZD3",
      "priority": 24,
      "severity": "needs-evidence",
      "recommendedAction": "request-raw-evidence",
      "status": "review-candidate",
      "window": {
        "startTs": "2023-10-13T16:00:00.000Z",
        "endTs": "2023-10-17T16:00:00.000Z",
        "durationDays": 5,
        "seasonSet": "autumn",
        "monthSet": "2023-10"
      },
      "evidenceSummary": {
        "utilityClass": "isolated-background-alert-run",
        "classificationMix": "hard-negative-no-positive-within-30d:5",
        "evidenceRowCount": 5,
        "immediatePositiveDays": 0,
        "greyZoneDays": 0,
        "within30Days": 0,
        "isolatedDays": 5,
        "maxBoosterScore": 0.5470855746219546
      },
      "autoReview": {
        "finalClass": "unclear",
        "useful": "unsure",
        "confidence": "low",
        "rule": "insufficient-auto-evidence",
        "rawEvidenceNeeded": "yes",
        "warning": "模型复核候选，需人工确认后发布。"
      }
    }
  ]
} as const;

export type BaijiabaoReviewQueueSnapshot = typeof baijiabaoReviewQueueSnapshot;
export type BaijiabaoReviewQueueItem = BaijiabaoReviewQueueSnapshot["items"][number];

